    <div class="dashboard">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <div class="box-account box-info">
            <div class="box-head">
                <h2><?php echo $this->__('Wholesale Download Section') ?></h2>
            </div>
        </div>
        <?php
		function remove_tag($str, $remove)  // $remove can be scalar or array 
		{ 
			while ((strpos($str, '< ') !== false) || (strpos($str, '/ ') !== false)) 
			{ 
				$str = str_replace(array('< ', '/ '), array('<', '/'), $str); 
			} 
			foreach ((array) $remove as $tag) 
			{ 
				$search_arr = array('<'  . strtolower($tag), '<'  . strtoupper($tag),  
				'</' . strtolower($tag), '</' . strtoupper($tag)); 
				foreach ($search_arr as $search) 
				{ 
					$start_pos = 0; 
					while (($start_pos = strpos($str, $search, $start_pos)) !== false) 
					{ 
						$end_pos = strpos($str, '>', $start_pos); 
						$len = $end_pos - $start_pos + 1; 
						$str = substr_replace($str, '', $start_pos, $len); 
					} 
				} 
			} 
			return $str; 
		}  
        ?>
    </div>