<script type="text/javascript">
var assurant_limit_state_msg = '<?php echo Assurant_Pro2_Model_Observer::LIMIT_STATE_MSG?>';
var assurant_invalid_token = '<?php echo Assurant_Pro2_Model_Connect_Curl::INVALID_TOKEN_MSG?>';
var assurant_accept_terms_alert = '<?php echo Mage::getStoreConfig('aintegration/setting/accept_terms_alert')?>';
var assurant_clean_url = '/pro2/submit/cleanassurant/';
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pro2/js/checkoutscript.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pro2/js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pro2/js/sweetalert.min.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('pro2/css/sweetalert.css') ?>"/>
